name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "59 23 * * 3"

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  unittests:
    name: ${{ matrix.os }}, ${{ matrix.environment-file }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        environment-file: [ci/latest.yaml]
    env:
      THUNDERFOREST: ${{ secrets.THUNDERFOREST }}
      JAWG: ${{ secrets.JAWG }}
      MAPBOX: ${{ secrets.MAPBOX }}
      MAPTILER: ${{ secrets.MAPTILER }}
      TOMTOM: ${{ secrets.TOMTOM }}
      OPENWEATHERMAP: ${{ secrets.OPENWEATHERMAP }}
      HEREV3: ${{ secrets.HEREV3 }}


    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: "latest"

      - name: Install xyzservices
        shell: bash -l {0}
        run: pip install .
        if: matrix.os != 'windows-latest'

      - name: Install xyzservices
        shell: powershell
        run: pip install .
        if: matrix.os == 'windows-latest'

      - name: run tests - bash
        shell: bash -l {0}
        run: pytest -v . --cov=xyzservices --cov-append --cov-report term-missing --cov-report xml --color=yes
        if: matrix.os != 'windows-latest'

      - name: run tests - powershell
        shell: powershell
        run: pytest -v . --cov=xyzservices --cov-append --cov-report term-missing --cov-report xml --color=yes
        if: matrix.os == 'windows-latest'

      - uses: codecov/codecov-action@v2
